export const SET_LOADING_STATE = 'SET_LOADING_STATE'
export const SET_SEARCH_FILTERS = 'SET_SEARCH_FILTERS'
export const HANDLE_SEARCH_INPUT = 'HANDLE_SEARCH_INPUT'
export const SUBMIT_SEARCH_REQUEST = 'SUBMIT_SEARCH_REQUEST'
